#ifndef CODEGEN_H
#define CODEGEN_H
#include "ast.h"
#include <sstream>
#include <string>
#include <memory>

class CodeGenerator {
private:
    std::ostringstream code;
    int indentLevel = 0;
    
    // Indent helper
    std::string indent() {
        return std::string(indentLevel * 4, ' ');
    }
    
    void increaseIndent() { indentLevel++; }
    void decreaseIndent() { indentLevel--; }
    
public:
    CodeGenerator() = default;
    
    // Generate Python code from AST
    std::string generate(BlockNode* program) {
        code.str("");
        code.clear();
        
        // Python header
        code << "#!/usr/bin/env python3\n";
        code << "# Generated by JHAMELA Compiler\n\n";
        
        // Generate statements
        for (auto& stmt : program->statements) {
            generateStatement(stmt.get());
        }
        
        return code.str();
    }
    
private:
    void generateStatement(StmtNode* stmt) {
        if (auto decl = dynamic_cast<VarDeclNode*>(stmt)) {
            generateVarDecl(decl);
        } else if (auto assign = dynamic_cast<AssignNode*>(stmt)) {
            generateAssign(assign);
        } else if (auto print = dynamic_cast<PrintNode*>(stmt)) {
            generatePrint(print);
        } else if (auto ifNode = dynamic_cast<IfNode*>(stmt)) {
            generateIf(ifNode);
        } else if (auto whileNode = dynamic_cast<WhileNode*>(stmt)) {
            generateWhile(whileNode);
        } else if (auto block = dynamic_cast<BlockNode*>(stmt)) {
            generateBlock(block);
        }
    }
    
    void generateVarDecl(VarDeclNode* decl) {
        // Variable declarations not needed in Python (dynamic typing)
        // But we can add a comment for clarity
        code << indent() << "# Declare: " << decl->name << "\n";
    }
    
    void generateAssign(AssignNode* assign) {
        code << indent() << assign->name << " = ";
        generateExpr(assign->expr.get());
        code << "\n";
    }
    
    void generatePrint(PrintNode* print) {
        code << indent() << "print(";
        generateExpr(print->expr.get());
        code << ")\n";
    }
    
    void generateIf(IfNode* ifNode) {
        code << indent() << "if ";
        generateExpr(ifNode->condition.get());
        code << ":\n";
        
        increaseIndent();
        if (ifNode->thenBranch) {
            generateBlock(ifNode->thenBranch.get());
        } else {
            code << indent() << "pass\n";
        }
        decreaseIndent();
        
        if (ifNode->elseBranch) {
            code << indent() << "else:\n";
            increaseIndent();
            generateBlock(ifNode->elseBranch.get());
            decreaseIndent();
        }
    }
    
    void generateWhile(WhileNode* whileNode) {
        code << indent() << "while ";
        generateExpr(whileNode->condition.get());
        code << ":\n";
        
        increaseIndent();
        if (whileNode->body) {
            generateBlock(whileNode->body.get());
        } else {
            code << indent() << "pass\n";
        }
        decreaseIndent();
    }
    
    void generateBlock(BlockNode* block) {
        if (block->statements.empty()) {
            code << indent() << "pass\n";
        } else {
            for (auto& stmt : block->statements) {
                generateStatement(stmt.get());
            }
        }
    }
    
    void generateExpr(ExprNode* expr) {
        if (auto num = dynamic_cast<NumberNode*>(expr)) {
            code << num->value;
        } else if (auto str = dynamic_cast<StringNode*>(expr)) {
            // Escape quotes
            std::string escaped = str->value;
            size_t pos = 0;
            while ((pos = escaped.find("\"", pos)) != std::string::npos) {
                escaped.replace(pos, 1, "\\\"");
                pos += 2;
            }
            code << "\"" << escaped << "\"";
        } else if (auto id = dynamic_cast<IdentifierNode*>(expr)) {
            code << id->name;
        } else if (auto binOp = dynamic_cast<BinaryOpNode*>(expr)) {
            code << "(";
            generateExpr(binOp->left.get());
            code << " " << binOp->op << " ";
            generateExpr(binOp->right.get());
            code << ")";
        }
    }
};

#endif
