#ifndef CODEGEN_H
#define CODEGEN_H
#include "ast.h"
#include <sstream>
#include <string>
#include <memory>
#include <stdexcept>

class CodeGenerator {
private:
    std::ostringstream code;
    int indentLevel = 0;

    std::string indent() { return std::string(indentLevel * 4, ' '); }
    void increaseIndent() { indentLevel++; }
    void decreaseIndent() { indentLevel--; }

public:
    CodeGenerator() = default;

    std::string generate(BlockNode* program) {
        code.str("");
        code.clear();
        code << "#!/usr/bin/env python3\n";
        code << "# Generated by JHAMELA Compiler\n\n";
        for (auto& stmt : program->statements)
            generateStatement(stmt.get());
        return code.str();
    }

private:
    void generateStatement(StmtNode* stmt) {
        if (auto s = dynamic_cast<VarDeclNode*>(stmt))      generateVarDecl(s);
        else if (auto s = dynamic_cast<AssignNode*>(stmt))  generateAssign(s);
        else if (auto s = dynamic_cast<PrintNode*>(stmt))   generatePrint(s);
        else if (auto s = dynamic_cast<IfNode*>(stmt))      generateIf(s);
        else if (auto s = dynamic_cast<WhileNode*>(stmt))   generateWhile(s);
        else if (auto s = dynamic_cast<BlockNode*>(stmt))   generateBlock(s);
    }

    void generateVarDecl(VarDeclNode* decl) {
        code << indent() << "# Declare: " << decl->name
             << " (" << decl->type << ")\n";
    }

    void generateAssign(AssignNode* assign) {
        code << indent() << assign->name << " = ";
        generateExpr(assign->expr.get());
        code << "\n";
    }

    void generatePrint(PrintNode* print) {
        code << indent() << "print(";
        generateExpr(print->expr.get());
        code << ")\n";
    }

    void generateIf(IfNode* ifNode) {
        code << indent() << "if ";
        generateExpr(ifNode->condition.get());
        code << ":\n";

        increaseIndent();
        if (ifNode->thenBranch) generateBlock(ifNode->thenBranch.get());
        else                    code << indent() << "pass\n";
        decreaseIndent();

        if (ifNode->elseBranch) {
            code << indent() << "else:\n";
            increaseIndent();
            generateBlock(ifNode->elseBranch.get());
            decreaseIndent();
        }
    }

    void generateWhile(WhileNode* whileNode) {
        code << indent() << "while ";
        generateExpr(whileNode->condition.get());
        code << ":\n";
        increaseIndent();
        if (whileNode->body) generateBlock(whileNode->body.get());
        else                 code << indent() << "pass\n";
        decreaseIndent();
    }

    void generateBlock(BlockNode* block) {
        if (block->statements.empty()) {
            code << indent() << "pass\n";
        } else {
            for (auto& stmt : block->statements)
                generateStatement(stmt.get());
        }
    }

    void generateExpr(ExprNode* expr) {
        if (expr == nullptr) throw std::runtime_error("Null expression in code generation");

        if (auto n = dynamic_cast<NumberNode*>(expr)) {
            code << n->value;
        }
        else if (auto b = dynamic_cast<BoolNode*>(expr)) {
            code << (b->value ? "True" : "False");
        }
        else if (auto s = dynamic_cast<StringNode*>(expr)) {
            code << "\"";
            for (char c : s->value) {
                if      (c == '\\') code << "\\\\";
                else if (c == '"')  code << "\\\"";
                else if (c == '\n') code << "\\n";
                else if (c == '\t') code << "\\t";
                else                code << c;
            }
            code << "\"";
        }
        else if (auto id = dynamic_cast<IdentifierNode*>(expr)) {
            code << id->name;
        }
        else if (auto u = dynamic_cast<UnaryOpNode*>(expr)) {
            code << "(" << u->op;
            generateExpr(u->operand.get());
            code << ")";
        }
        else if (auto b = dynamic_cast<BinaryOpNode*>(expr)) {
            code << "(";
            generateExpr(b->left.get());
            code << " " << b->op << " ";
            generateExpr(b->right.get());
            code << ")";
        }
        else {
            throw std::runtime_error("Unknown expression type in code generation");
        }
    }
};

#endif