#!/usr/bin/env python3
# Generated by JHAMELA Compiler

# Declare: ক (পূর্ণসংখ্যা)
# Declare: খ (পূর্ণসংখ্যা)
ক = 10
খ = 3
print((ক + খ))
print((ক - খ))
print((ক * খ))
print((ক / খ))
print((ক + (খ * 2)))
print(((ক + খ) * 2))
