#!/usr/bin/env python3
# Generated by JHAMELA Compiler

# Declare: ক (পূর্ণসংখ্যা)
# Declare: বড় (সত্যমূল্য)
ক = 5
বড় = (ক > 3)
print(ক)
print(বড়)
if বড়:
    print("সংখ্যাটি বড়")
else:
    print("সংখ্যাটি ছোট")
while (ক > 0):
    print(ক)
    ক = (ক - 1)
